version: '3'

services:
    mongo_import:
        image: mongo
        container_name: imersif_mongo_import
        command: bash -c '/home/scripts/wait-mongo.sh && /home/scripts/restore.sh'
        volumes:
            - ./scripts:/home/scripts
            - ./data/backup:/data/backup
        depends_on:
            - mongo
