version: '3'

services:
  strapi:
    command: bash -c 'yarn && NODE_ENV=production yarn build && NODE_ENV=production yarn start'
  next:
    image: node
    container_name: imersif_next
    depends_on:
      - strapi
    environment:
      NEXT_PUBLIC_STRAPI_URL: http://$HOST:$STRAPI_PORT
      NEXT_DOCKER_STRAPI_URL: http://imersif_strapi:$STRAPI_PORT
    command: bash -c 'yarn && /home/scripts/wait.sh http://imersif_strapi:$STRAPI_PORT && yarn build && yarn start'
    expose:
      - '$NEXT_PORT'
    ports:
      - '$NEXT_PORT:$NEXT_PORT'
    user: node
    volumes:
      - ./next:/home/node/app
      - ./scripts:/home/scripts
    working_dir: /home/node/app
  ngnix:
    build: ./nginx
    container_name: imersif_nginx
    depends_on:
      - next
    ports:
      - '80:80'
