version: '3'

services:
    mongo:
        image: mongo
        container_name: imersif_mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: strapi
            MONGO_INITDB_ROOT_PASSWORD: strapi
        ports:
            - '27017:27017'
    strapi:
        image: strapi/strapi
        container_name: imersif_strapi
        environment:
            DATABASE_CLIENT: mongo
            DATABASE_NAME: strapi
            DATABASE_HOST: mongo
            DATABASE_PORT: 27017
            DATABASE_USERNAME: strapi
            DATABASE_PASSWORD: strapi
            HOST: $STRAPI_HOST
            PORT: $STRAPI_PORT
        links:
            - mongo:mongo
        expose:
            - '$STRAPI_PORT'
        ports:
            - '$STRAPI_PORT:$STRAPI_PORT'
