version: '3'

services:
    frontend:
        image: node
        container_name: imersif_frontend
        depends_on:
            - strapi
        environment:
            NEXT_PUBLIC_STRAPI_URL: http://imersif_strapi:1337
        command: bash -c 'yarn && yarn build && yarn start'
        expose:
            - '3000'
        ports:
            - '3000:3000'
        user: node
        volumes:
            - ./frontend:/home/node/app
        working_dir: /home/node/app
    ngnix:
        build: ./nginx
        container_name: imersif_nginx
        ports:
            - '80:80'