version: '3'

services:
    mongo:
        volumes:
            - mongodata:/data/db
            - ./data/backup:/data/backup
    strapi:
        volumes:
            - imersif_sync_strapi:/srv/app:nocopy
volumes:
    mongodata:
    imersif_sync_strapi:
        external: true
