version: '3'

services:
  strapi:
    command: bash -c 'yarn && NODE_ENV=production yarn build && NODE_ENV=production yarn start'
  next:
    image: node
    container_name: imersif_next
    depends_on:
      - strapi
    command: bash -c 'yarn && /home/scripts/wait.sh http://imersif_strapi:$STRAPI_PORT && yarn build && yarn start'
    expose:
      - '$NEXT_PORT'
    ports:
      - '$NEXT_PORT:$NEXT_PORT'
    user: node
    volumes:
      - ./next:/home/node/app
      - ./scripts:/home/scripts
    working_dir: /home/node/app
  nginx:
    image: nginx
    container_name: imersif_nginx
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    ports:
      - '80:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
